### ISSUE TITLE
Is the link to test database in the README correct?

### ISSUE THREAD

**Issue by defunctl** [eugenezadorin/airtable-php#8]
Hi!

I wanted to provide some pull requests for this library.

I copied the [readonly database](https://airtable.com/shrs2bB37sScbDuLX) to my own account after forking this repo and 11 of the 83 tests failed.

Is there something wrong with the database or are the tests also failing on your end?

![image](https://user-images.githubusercontent.com/1066195/208191837-6879b1c7-8610-4351-b32a-61941361e665.png)

Please let me know.

**Comment by eugenezadorin** [comment]
Hello! I've got the same problem with a cloned database.

Tests failed due to the fact that I did not explicitly specify the order of records. For some reason, in my own test database, the records came in the expected order and the tests didn't fail.

In the cloned database, the order of the records was different. Now I specify sorting explicitly, so everything should work.

Thank you for participating!

**Comment by defunctl** [comment]
All passing in my fork now, thanks!
